config/routes.rb
Rails.application.routes.draw do
  get "testing/index"
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  root "dashboard#index"
  # --- Trader routes ---
  # Portfolio (optionally with :stock_id param)
  resources :portfolios do
    member do
      post :sell
    end
  end
  # --- Stocks routes ---
  resources :stocks do
    collection do
      post :update_prices
    end
  end
  # dashboard
  get "dashboard", to: "dashboard#index"
  # Transactions
  get "/transactions", to: "transactions#index", as: :transactions
  # Trades (form + buy/sell actions)
  get  "/trades/new", to: "trades#new",  as: :new_trade
  post "/trades/buy", to: "trades#buy",  as: :buy_trade
  post "/trades/sell", to: "trades#sell", as: :sell_trade
  get "/trade_logs", to: "trade_logs#index", as: :trade_logs
  # Wallet routes
  get "/wallet",        to: "wallets#show",   as: :wallet
  post "/wallet/top_up", to: "wallets#top_up", as: :top_up_wallet
  post "/wallet/withdraw", to: "wallets#withdraw", as: :withdraw_wallet
  # User routes
  resources :users, only: [] do
    member do
      patch :apply_broker
    end
  end
  # --- Admin routes ---
  namespace :admin do
    resources :transactions, only: :index
    resources :users do
      collection do
        get :index
        get :pending_approvals
        get :all_users
      end
      member do
        patch :approve
        patch :revoke
        patch :approve_broker
        patch :reject_broker
        delete :delete
      end
    end
  end
  get "test_quote", to: "stocks#test_quote"
  post "stocks/update_prices", to: "stocks#update_prices", as: :update_prices
  # Health check
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/user.rb
# app/models/user.rb
class User < ApplicationRecord
  # --- Devise modules ---
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  # --- Enums ---
  enum :role, { admin: 0, trader: 1, broker: 2 }
  enum :broker_status, { no_application: 0, broker_pending: 1, broker_approved: 2, broker_rejected: 3 }

  # --- Associations ---
  has_one  :wallet,     dependent: :destroy
  has_many :portfolios, dependent: :destroy
  has_many :stocks, through: :portfolios
  has_many :trade_logs, dependent: :destroy

  # --- Callbacks ---
  after_create :ensure_wallet!
  before_create :set_default_role
  before_update :set_approval_date, if: :will_save_change_to_role?

  # --- Instance methods ---
  def approved?
    approved
  end

  def ensure_wallet!
    wallet || create_wallet!(balance: 0)
  end

  def day_profit_loss
    trade_logs.sum do |log|
      next 0 unless log.stock && log.stock.price_change
      direction = log.transaction_type == "buy" ? 1 : -1
      log.stock.price_change.to_f * log.quantity.to_f * direction
    end
  end

  private

  def set_default_role
    self.role ||= :trader
  end

  def set_approval_date
    self.approval_date = approved? ? Time.current : nil
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_admin!
  before_action :set_user, only: [ :approve, :revoke, :show, :approve_broker, :reject_broker, :show, :edit, :update, :delete ]

  def index
    @allusers = User.all
    @users = User.where(approved: false, role: :trader)
    @pending_brokers = User.where(broker_status: :broker_pending, role: :trader)
    @approved_brokers = User.where(broker_status: :broker_approved)
    @last_stock_update = Stock.where.not(last_updated_at: nil).maximum(:last_updated_at)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.confirm
      redirect_to admin_user_path(@user), notice: "User created successfully."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @user
  end

  def edit
    @user
  end

  def update
    if @user.update(user_edit_params)
      redirect_to admin_user_path(@user), notice: "User updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end


  def delete
    @user.destroy
    redirect_to admin_users_path, notice: "User deleted."
  end

  def all_users
    @allusers = User.all
  end
  def pending_approvals
    @users = User.where(approved: false, role: :trader)
    @pending_brokers = User.where(broker_status: :broker_pending, role: :trader)
  end

  def approve
    if @user.trader? && !@user.approved?
      @user.update!(approved: true, approval_date: Time.current)
      @user.confirm unless @user.confirmed?
      TraderMailer.approval_email(@user).deliver_now
      redirect_to admin_users_path, notice: "#{@user.username} approved as trader and email sent!"
    else
      redirect_to admin_users_path, alert: "#{@user.username} is already approved."
    end
  end

  def revoke
    if @user.trader? && @user.approved?
      @user.update!(approved: false, approval_date: nil)
      redirect_to admin_users_path, alert: "#{@user.username}'s approval revoked."
    else
      redirect_to admin_users_path, alert: "#{@user.username} is not an approved trader."
    end
  end

  def approve_broker
    if @user.trader? && @user.broker_pending?
      @user.update!(role: :broker, broker_status: :broker_approved, broker_approval_date: Time.current)
      redirect_to admin_users_path, notice: "#{@user.username} approved as broker and email sent!"
    else
      redirect_to admin_users_path, alert: "Cannot approve broker for this user."
    end
  end

  def reject_broker
    if @user.trader? && @user.pending?
      @user.update!(broker_status: :broker_rejected)
      redirect_to admin_users_path, alert: "#{@user.username}'s broker application rejected."
    else
      redirect_to admin_users_path, alert: "Cannot reject broker for this user."
    end
  end

  private

  def ensure_admin!
    redirect_to root_path, alert: "Not authorized" unless current_user&.admin?
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :username, :first_name, :last_name, :password, :approved)
  end

  def user_edit_params
    params.require(:user).permit(:email, :username, :first_name, :last_name)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :first_name, :last_name)
  end
end
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

# GET /resource/sign_up
# def new
#   super
# end

# POST /resource
# def create
#   super
# end

# GET /resource/edit
# def edit
#   super
# end

# PUT /resource
# def update
#   super
# end

# DELETE /resource
# def destroy
#   super
# end

# GET /resource/cancel
# Forces the session data which is usually expired after sign
# in to be expired now. This is useful if the user wants to
# cancel oauth signing in/up in the middle of the process,
# removing all OAuth session data.
# def cancel
#   super
# end

# protected

# If you have extra params to permit, append them to the sanitizer.
# def configure_sign_up_params
#   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
# end

# If you have extra params to permit, append them to the sanitizer.
# def configure_account_update_params
#   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
# end

# The path used after sign up.
# def after_sign_up_path_for(resource)
#   super(resource)
# end

# The path used after sign up for inactive accounts.
# def after_inactive_sign_up_path_for(resource)
#   super(resource)
# end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def dashboard
  end

  def apply_broker
    if current_user.trader? && current_user.no_application?
      current_user.update!(broker_status: :broker_pending)
      redirect_to root_path, notice: "Broker application submitted."
    else
      redirect_to root_path, alert: "Cannot apply for broker."
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/all_users.html.erb
<div class="container-xl px-3 px-md-4 px-lg-5">

  <div class="d-flex justify-content-between align-items-center mb-3">
    <h4 class="fw-semibold">All Users</h4>
    <%= link_to new_admin_user_path, class: "btn btn-primary d-flex align-items-center gap-2" do %>
      <i class="bi bi-plus-lg"></i> Add User
    <% end %>
  </div>

  <div class="card border-0 shadow-sm">
    <div class="card-body px-4">

      <div class="table-responsive">
        <table class="table align-middle">
          <thead class="table-light">
            <tr>
              <th>User</th>
              <th>Email</th>
              <th>Role</th>
              <th>Created</th>
              <th>Status</th>
              <th class="text-end">Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @allusers.where(role: [:trader, :broker]).each do |user| %>
              <tr>
                <!-- User / Avatar -->
                <td>
                  <div class="d-flex align-items-center">
                    <% if user.approved? %>
                      <div class="rounded-circle bg-success-subtle text-success d-flex align-items-center justify-content-center me-3" style="width:36px;height:36px;">
                        <i class="bi bi-person-fill fs-5"></i>
                      </div>
                    <% else %>
                      <div class="rounded-circle bg-warning-subtle text-warning d-flex align-items-center justify-content-center me-3" style="width:36px;height:36px;">
                        <i class="bi bi-person-fill fs-5"></i>
                      </div>
                    <% end %>
                    <div>
                      <div class="fw-semibold"><%= user.username.presence || "No Name" %></div>
                      <small class="text-secondary">ID: <%= user.id %></small>
                    </div>
                  </div>
                </td>

                <!-- Email -->
                <td><%= user.email %></td>

                <!-- Role -->
                <td><%= user.role.humanize %></td>

                <!-- Created -->
                <td><%= user.created_at.strftime("%-m/%-d/%Y") %></td>

                <!-- Status -->
                <td>
                  <% if user.approved? %>
                    <span class="badge rounded-pill bg-success-subtle text-success d-inline-flex align-items-center gap-1">
                      <span class="rounded-circle bg-success" style="width:8px;height:8px;"></span> Active
                    </span>
                  <% else %>
                    <span class="badge rounded-pill bg-warning-subtle text-warning d-inline-flex align-items-center gap-1">
                      <span class="rounded-circle bg-warning" style="width:8px;height:8px;"></span> Pending
                    </span>
                  <% end %>
                </td>

                <!-- Actions -->
                <td class="text-end">
                  <div class="btn-group" role="group">
                    <%= link_to admin_user_path(user), class: "btn btn-sm btn-light border", title: "View" do %>
                      <i class="bi bi-eye"></i>
                    <% end %>

                    <%= link_to edit_admin_user_path(user), class: "btn btn-sm btn-light border", title: "Edit" do %>
                      <i class="bi bi-pencil"></i>
                    <% end %>

                    <%= button_to delete_admin_user_path(user),
                          method: :delete,
                          form: { data: { turbo_confirm: "Are you sure?" } },
                          class: "btn btn-sm btn-light border",
                          title: "Delete" do %>
                      <i class="bi bi-trash"></i>
                    <% end %>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

    </div>
  </div>
</div>

<style>
  .bg-success-subtle  { background:#e9f7ef!important; color:#198754!important; }
  .bg-warning-subtle  { background:#fff3cd!important; color:#b58100!important; }
</style>

app/views/admin/users/index.html.erb
<%# Admin Dashboard - index %>

<div class="container-xl pt-4 pb-5 px-3 px-md-4 px-lg-5"><!-- comfy spacing below navbar -->

  <div class="row g-3 mb-4">
    <div class="col-12 col-md-3">
      <div class="card shadow-sm border-0 h-100">
        <div class="card-body d-flex justify-content-between align-items-center">
          <div>
            <div class="text-secondary small">Total Users</div>
            <div class="h4 mb-0 fw-bold"><%= @allusers.where(role: [:trader, :broker]).count %></div>
          </div>
          <div class="rounded-3 bg-primary-subtle text-primary p-3">
            <i class="bi bi-people-fill fs-4"></i>
          </div>
        </div>
      </div>
    </div>

    <div class="col-12 col-md-3">
      <div class="card shadow-sm border-0 h-100">
        <div class="card-body d-flex justify-content-between align-items-center">
          <div>
            <div class="text-secondary small">Pending Traders</div>
            <div class="h4 mb-0 fw-bold"><%= @users.count %></div>
          </div>
          <div class="rounded-3 bg-warning-subtle text-warning p-3">
            <i class="bi bi-clock-history fs-4"></i>
          </div>
        </div>
      </div>
    </div>

    <div class="col-12 col-md-3">
      <div class="card shadow-sm border-0 h-100">
        <div class="card-body d-flex justify-content-between align-items-center">
          <div>
            <div class="text-secondary small">Pending Brokers</div>
            <div class="h4 mb-0 fw-bold"><%= @pending_brokers.count %></div>
          </div>
          <div class="rounded-3 bg-warning-subtle text-warning p-3">
            <i class="bi bi-person-x-fill fs-4"></i>
          </div>
        </div>
      </div>
    </div>

    <div class="col-12 col-md-3">
      <div class="card shadow-sm border-0 h-100">
        <div class="card-body d-flex justify-content-between align-items-center">
          <div>
            <div class="text-secondary small">Approved Brokers</div>
            <div class="h4 mb-0 fw-bold"><%= @approved_brokers.count %></div>
          </div>
          <div class="rounded-3 bg-success-subtle text-success p-3">
            <i class="bi bi-person-check-fill fs-4"></i>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Quick Actions -->
  <div class="card border-0 shadow-sm mb-4">
    <div class="card-body px-4">
      <h5 class="card-title mb-3">Quick Actions</h5>
      <div class="d-flex flex-wrap gap-3">
        <%= link_to new_admin_user_path, class: "btn btn-primary-subtle border-0 btn-lg d-flex align-items-center gap-2" do %>
          <i class="bi bi-plus-lg"></i> Add New User
        <% end %>

        <%= link_to pending_approvals_admin_users_path, class: "btn btn-warning-subtle border-0 btn-lg d-flex align-items-center gap-2" do %>
          <i class="bi bi-clock-history"></i> Review Pending
        <% end %>

        <%= link_to all_users_admin_users_path, class: "btn btn-success-subtle border-0 btn-lg d-flex align-items-center gap-2" do %>
          <i class="bi bi-people"></i> View All Users
        <% end %>

        <%= link_to admin_transactions_path, class: "btn btn-purple-subtle border-0 btn-lg d-flex align-items-center gap-2" do %>
          <i class="bi bi-activity"></i> View Transactions
        <% end %>

        <!-- Refresh + last updated -->
        <div class="d-flex align-items-center gap-2 flex-wrap">
          <%= button_to update_prices_path,
                method: :post,
                class: "btn btn-danger-subtle border-0 btn-lg d-flex align-items-center gap-2 m-0" do %>
            <i class="bi bi-arrow-clockwise"></i> Refresh Prices
          <% end %>

          <% if Stock.any? %>
            <small class="text-muted">
              Last updated:
              <%= Stock.maximum(:updated_at).in_time_zone("Asia/Manila").strftime("%b. %-d, %Y %I:%M%p") %>
            </small>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <!-- Recent Activity -->
  <div class="card border-0 shadow-sm">
    <div class="card-body px-4">
      <h5 class="card-title mb-3">Recent Activity</h5>

      <% if @recent_activities.present? %>
        <div class="list-group list-group-flush">
          <% @recent_activities.each do |a| %>
            <% dot_class =
                case a[:type]
                when :new_user then 'bg-success'
                when :approved then 'bg-primary'
                when :application then 'bg-warning'
                else 'bg-secondary'
                end %>
            <div class="list-group-item d-flex align-items-center py-3">
              <span class="rounded-circle me-3 d-inline-block <%= dot_class %>" style="width:10px;height:10px;"></span>

              <div class="flex-grow-1">
                <div><%= a[:message] %></div>
              </div>
              <small class="text-secondary ms-3"><%= time_ago_in_words(a[:created_at]) %> ago</small>
            </div>
          <% end %>
        </div>
      <% else %>
        <div class="text-secondary">No recent activity.</div>
      <% end %>
    </div>
  </div>

</div><!-- /container -->

<!-- button styles + spacing tweaks -->
<style>
  .btn-primary-subtle  { background:#e7f1ff; color:#0d6efd; }
  .btn-warning-subtle  { background:#fff3cd; color:#b58100; }
  .btn-success-subtle  { background:#e9f7ef; color:#198754; }
  .btn-purple-subtle   { background:#f3e8ff; color:#6f42c1; }
  .btn-danger-subtle   { background:#fde2e1; color:#dc3545; }

  /* Add a touch of horizontal padding back to flush list items */
  .list-group-flush > .list-group-item {
    padding-left: 1rem;
    padding-right: 1rem;
  }

  .bg-primary-subtle   { background:#e7f1ff!important; color:#0d6efd!important; }
  .bg-success-subtle   { background:#e9f7ef!important; color:#198754!important; }
  .bg-warning-subtle   { background:#fff3cd!important; color:#b58100!important; }
</style>

app/views/admin/users/pending_approvals.html.erb
<div class="container-xl pt-4 pb-5 px-3 px-md-4 px-lg-5">

  <!-- Trader Approvals -->
  <div class="d-flex align-items-center gap-2 mb-2 mt-1">
    <i class="bi bi-person-badge text-primary"></i>
    <h4 class="fw-semibold mb-0">Trader Approvals (<%= @users.size %>)</h4>
  </div>

  <% if @users.blank? %>
    <div class="card border-0 shadow-sm mb-5">
      <div class="card-body px-4">
        <div class="alert alert-light border mb-0">No pending trader applications.</div>
      </div>
    </div>
  <% else %>
    <div class="row g-4 mb-5">
      <% @users.each do |user| %>
        <div class="col-12 col-md-6">
          <div class="card border-warning rounded-4 shadow-sm h-100">
            <div class="card-body px-4">
              <div class="d-flex justify-content-between align-items-start mb-3">
                <div class="d-flex align-items-center">
                  <div class="rounded-circle bg-warning-subtle text-warning d-flex align-items-center justify-content-center me-3" style="width:40px;height:40px;">
                    <i class="bi bi-alarm fs-5"></i>
                  </div>
                  <div>
                    <div class="fw-semibold">
                      <%= ([user.first_name, user.last_name].map(&:presence).compact.join(" ").presence ||
                           user.username.presence ||
                           user.email.split("@").first) %>
                    </div>
                    <small class="text-secondary">Application ID: <%= user.id %></small>
                  </div>
                </div>
                <span class="badge rounded-pill bg-primary-subtle text-primary">
                  <i class="bi bi-person-badge me-1"></i> Trader Application
                </span>
              </div>

              <ul class="list-unstyled mb-3">
                <li class="mb-1">
                  <i class="bi bi-envelope me-2 text-secondary"></i> <%= user.email %>
                </li>
                <li class="mb-1">
                  <i class="bi bi-calendar2 me-2 text-secondary"></i> Applied <%= time_ago_in_words(user.created_at) %> ago
                </li>
                <li class="mb-1 d-flex align-items-center">
                  <span class="rounded-circle d-inline-block me-2 bg-warning" style="width:8px;height:8px;"></span>
                  <span class="text-secondary">Status: Pending Review</span>
                </li>
              </ul>

              <div class="d-flex flex-wrap gap-2">
                <%= link_to admin_user_path(user), class: "btn btn-light border d-flex align-items-center gap-2" do %>
                  <i class="bi bi-eye"></i> View Details
                <% end %>
                <%= button_to approve_admin_user_path(user),
                      method: :patch,
                      class: "btn btn-warning text-dark d-flex align-items-center gap-2",
                      form: { data: { turbo_confirm: "Approve this Trader application?" } } do %>
                  <i class="bi bi-check2-circle"></i> Approve as Trader
                <% end %>
                <%= button_to delete_admin_user_path(user),
                      method: :delete,
                      class: "btn btn-danger d-flex align-items-center gap-2",
                      form: { data: { turbo_confirm: "Reject and remove this Trader application?" } } do %>
                  <i class="bi bi-x-circle"></i> Reject
                <% end %>
              </div>

            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>

  <!-- Broker Approvals -->
  <div class="d-flex align-items-center gap-2 mb-2">
    <i class="bi bi-exclamation-triangle text-warning"></i>
    <h4 class="fw-semibold mb-0">Broker Approvals (<%= @pending_brokers.size %>)</h4>
  </div>

  <% if @pending_brokers.blank? %>
    <div class="card border-0 shadow-sm">
      <div class="card-body px-4">
        <div class="alert alert-light border mb-0">No pending broker applications.</div>
      </div>
    </div>
  <% else %>
    <div class="row g-4">
      <% @pending_brokers.each do |user| %>
        <div class="col-12 col-md-6">
          <div class="card border-warning rounded-4 shadow-sm h-100">
            <div class="card-body px-4">
              <div class="d-flex justify-content-between align-items-start mb-3">
                <div class="d-flex align-items-center">
                  <div class="rounded-circle bg-warning-subtle text-warning d-flex align-items-center justify-content-center me-3" style="width:40px;height:40px;">
                    <i class="bi bi-alarm fs-5"></i>
                  </div>
                  <div>
                    <div class="fw-semibold">
                      <%= ([user.first_name, user.last_name].map(&:presence).compact.join(" ").presence ||
                           user.username.presence ||
                           user.email.split("@").first) %>
                    </div>
                    <small class="text-secondary">Application ID: <%= user.id %></small>
                  </div>
                </div>
                <span class="badge rounded-pill bg-warning-subtle text-warning">
                  <i class="bi bi-exclamation-triangle me-1"></i> Broker Application
                </span>
              </div>

              <ul class="list-unstyled mb-3">
                <li class="mb-1">
                  <i class="bi bi-envelope me-2 text-secondary"></i> <%= user.email %>
                </li>
                <li class="mb-1">
                  <i class="bi bi-calendar2 me-2 text-secondary"></i> Applied <%= time_ago_in_words(user.created_at) %> ago
                </li>
                <li class="mb-1 d-flex align-items-center">
                  <span class="rounded-circle d-inline-block me-2 bg-warning" style="width:8px;height:8px;"></span>
                  <span class="text-secondary">Status: Broker Pending</span>
                </li>
              </ul>

              <div class="d-flex flex-wrap gap-2">
                <%= link_to admin_user_path(user), class: "btn btn-light border d-flex align-items-center gap-2" do %>
                  <i class="bi bi-eye"></i> View Details
                <% end %>
                <%= button_to approve_broker_admin_user_path(user),
                      method: :patch,
                      class: "btn btn-warning text-dark d-flex align-items-center gap-2",
                      form: { data: { turbo_confirm: "Approve this Broker application?" } } do %>
                  <i class="bi bi-check2-circle"></i> Approve as Broker
                <% end %>
                <%= button_to reject_broker_admin_user_path(user),
                      method: :patch,
                      class: "btn btn-danger d-flex align-items-center gap-2",
                      form: { data: { turbo_confirm: "Reject this Broker application?" } } do %>
                  <i class="bi bi-x-circle"></i> Reject
                <% end %>
              </div>

            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>

</div>

<style>
  .bg-primary-subtle{ background:#e7f1ff!important; color:#0d6efd!important; }
  .bg-warning-subtle{ background:#fff3cd!important; color:#b58100!important; }
</style>